2022-11-09 15:15:19,340 - root - INFO - Dev Mode: Initiating Connection to RabbitMQ Instance
2022-11-09 15:15:23,426 - root - ERROR - Dev Mode: Connection to RabbitMQ unsucesfull, retying in 5 seconds
2022-11-09 15:15:28,435 - root - INFO - Dev Mode: Initiating Connection to RabbitMQ Instance
2022-11-09 15:15:32,526 - root - ERROR - Dev Mode: Connection to RabbitMQ unsucesfull, retying in 5 seconds
2022-11-09 15:15:37,528 - root - INFO - Dev Mode: Initiating Connection to RabbitMQ Instance
2022-11-09 15:15:37,542 - root - ERROR - Dev Mode: Connection to RabbitMQ unsucesfull, retying in 5 seconds
2022-11-09 15:15:42,558 - root - INFO - Dev Mode: Initiating Connection to RabbitMQ Instance
2022-11-09 15:15:42,585 - root - INFO - Dev Mode: Initiating Connection to RabbitMQ Instance
2022-11-09 15:15:42,599 - root - INFO -  [*] Waiting for messages. To exit press CTRL+C
2022-11-09 15:15:42,611 - root - DEBUG - Connection active
2022-11-09 15:15:42,615 - root - INFO - Recieved CMC_Q02_MAT_PLANT_ATTR.csv
2022-11-09 15:15:42,642 - root - INFO - File CMC_Q02_MAT_PLANT_ATTR.csv stored successfully
2022-11-09 15:15:42,643 - root - INFO -  [*] Waiting for messages.
2022-11-09 15:15:42,657 - root - DEBUG - Connection active
2022-11-09 15:15:42,661 - root - INFO - Recieved CMC_Q02_TCURR.csv
2022-11-09 15:15:42,670 - root - INFO - File CMC_Q02_TCURR.csv stored successfully
2022-11-09 15:15:42,670 - root - INFO -  [*] Waiting for messages.
2022-11-09 15:15:42,681 - root - DEBUG - Connection active
2022-11-09 15:15:42,682 - root - INFO - Recieved dads.txt
2022-11-09 15:15:42,683 - root - INFO - File dads.txt stored successfully
2022-11-09 15:15:42,684 - root - INFO -  [*] Waiting for messages.
2022-11-09 15:15:42,692 - root - DEBUG - Connection active
2022-11-09 15:15:42,693 - root - INFO - Recieved fdsfdsf.txt
2022-11-09 15:15:42,694 - root - INFO - File fdsfdsf.txt stored successfully
2022-11-09 15:15:42,695 - root - INFO -  [*] Waiting for messages.
2022-11-09 15:15:42,707 - root - DEBUG - Connection active
2022-11-09 15:15:42,708 - root - INFO - Recieved mike.txt
2022-11-09 15:15:42,709 - root - INFO - File mike.txt stored successfully
2022-11-09 15:15:42,710 - root - INFO -  [*] Waiting for messages.
2022-11-09 15:15:42,721 - root - DEBUG - Connection active
2022-11-09 15:15:42,721 - root - INFO - Recieved one.txt
2022-11-09 15:15:42,723 - root - INFO - File one.txt stored successfully
2022-11-09 15:15:42,723 - root - INFO -  [*] Waiting for messages.
2022-11-09 15:16:07,609 - root - ERROR - Unknown Connection Failure, network might be down..
2022-11-09 15:16:07,617 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\rfranqui\OneDrive - Entegris\Documents\P\Projects\RabbitMQ\recieve.py", line 144, in main
    channel.start_consuming()
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 1883, in start_consuming
    self._process_data_events(time_limit=None)
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 2044, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 842, in process_data_events
    self._flush_output(common_terminator)
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 514, in _flush_output
    self._impl.ioloop.poll()
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\select_connection.py", line 579, in poll
    self._poller.poll()
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\select_connection.py", line 953, in poll
    read, write, error = select.select(
KeyboardInterrupt

2022-11-09 15:16:07,618 - root - INFO - Dev Mode: Initiating Connection to RabbitMQ Instance
2022-11-09 15:16:07,645 - root - INFO - Dev Mode: Initiating Connection to RabbitMQ Instance
2022-11-09 15:16:07,657 - root - INFO -  [*] Waiting for messages. To exit press CTRL+C
2022-11-09 15:16:12,667 - root - ERROR - Unknown Connection Failure, network might be down..
2022-11-09 15:16:12,668 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\rfranqui\OneDrive - Entegris\Documents\P\Projects\RabbitMQ\recieve.py", line 144, in main
    channel.start_consuming()
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 1883, in start_consuming
    self._process_data_events(time_limit=None)
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 2044, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 842, in process_data_events
    self._flush_output(common_terminator)
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 514, in _flush_output
    self._impl.ioloop.poll()
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\select_connection.py", line 579, in poll
    self._poller.poll()
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\select_connection.py", line 953, in poll
    read, write, error = select.select(
KeyboardInterrupt

2022-11-09 15:16:12,669 - root - INFO - Dev Mode: Initiating Connection to RabbitMQ Instance
2022-11-09 15:16:12,695 - root - INFO - Dev Mode: Initiating Connection to RabbitMQ Instance
2022-11-09 15:16:12,708 - root - INFO -  [*] Waiting for messages. To exit press CTRL+C
2022-11-09 15:16:17,714 - root - ERROR - Unknown Connection Failure, network might be down..
2022-11-09 15:16:17,715 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\rfranqui\OneDrive - Entegris\Documents\P\Projects\RabbitMQ\recieve.py", line 144, in main
    channel.start_consuming()
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 1883, in start_consuming
    self._process_data_events(time_limit=None)
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 2044, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 842, in process_data_events
    self._flush_output(common_terminator)
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 514, in _flush_output
    self._impl.ioloop.poll()
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\select_connection.py", line 579, in poll
    self._poller.poll()
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\select_connection.py", line 953, in poll
    read, write, error = select.select(
KeyboardInterrupt

2022-11-09 15:16:17,716 - root - INFO - Dev Mode: Initiating Connection to RabbitMQ Instance
2022-11-09 15:16:17,766 - root - INFO - Dev Mode: Initiating Connection to RabbitMQ Instance
2022-11-09 15:16:17,780 - root - INFO -  [*] Waiting for messages. To exit press CTRL+C
